### ISSUE TITLE
Plugin Failed to Compile

### ISSUE THREAD

**Issue by wrsgwergergwer** [wootguy/ChatSounds#1]
https://github.com/wootguy/ChatSounds/blob/19e223a0ceb77212326112fb8216b3d54f3f1b44/ChatSounds.as#L316
From AS Log:
1 plugin(s) failed compilation
Not allowed: in section '/home/container/svencoop/scripts/plugins/ChatSounds/ChatSounds.as', at (316, 5): Function ReadSounds:
Message: Null pointer access
ERROR: CASBaseCallable::Call: Execution of function '::PluginInit' failed!
ERROR: Plugins must implement a PluginInit function!

**Comment by wootguy** [comment]
create the config file
https://github.com/wootguy/ChatSounds/tree/master#config

**Comment by z7indeed** [comment]
I also have this problem, i already created the file but the plugin still seems to not be able to read it.
![image](https://github.com/wootguy/ChatSounds/assets/134897125/5dbaedd4-096b-43e5-bd1e-34065b530781)

**Comment by wrsgwergergwer** [comment]
Going to necrobump this: After creating the config, plugin worked fine until yesterday. Now Im getting an error:
Not allowed: in section '/home/container/svencoop/scripts/plugins/ChatSounds/ChatSounds.as', at (154, 3): Function MapInit:
Message: Null pointer access
ERROR: CASBaseCallable::Call: Execution of function '::MapInit' failed!
The plugin successfully loads in but isnt functional at all, any idea why this could be?

**Comment by wrsgwergergwer** [comment]
Alright so after fucking with it for a while, straight up reinstalling everything fresh fixed all the issues. Ill close this thread now.

**Comment by wrsgwergergwer** [comment]
Alright so after fucking with it for a while, nuking all plugin related files, reinstalling it all fresh fixed all issues, Ill close this thread now.
